title:
  en: Noah Zhou | Academic Homepage
  zh: 周方亚诺 | 个人主页
page-top-title:
  en: Noah Zhou
  zh: 周方亚诺
top-section-bg-text:
  en: Stand by what is right, unwavering for life.
  zh: 择善固执，终生不渝
home-subtitle:
  en: Noah Zhou &ensp;|&ensp; Software Engineering + Business Administration
  zh: 周方亚诺 &ensp;|&ensp; 软件工程 + 工商管理
nav-home:
  en: Home
  zh: 主页
nav-awards:
  en: Awards
  zh: 奖励荣誉
nav-experience:
  en: Experience
  zh: 项目经历
nav-publications:
  en: Publications
  zh: 论文与成果
nav-portfolio:
  en: Portfolio
  zh: 作品集
lang-zh:
  en: 中文
  zh: 中文
lang-en:
  en: English
  zh: English
awards-subtitle:
  en: <i class="bi bi-award-fill"></i> Awards
  zh: <i class="bi bi-award-fill"></i> 奖励荣誉
experience-subtitle:
  en: <i class="bi bi-briefcase-fill"></i> Experience
  zh: <i class="bi bi-briefcase-fill"></i> 项目经历
publications-subtitle:
  en: <i class="bi bi-file-text-fill"></i> Publications
  zh: <i class="bi bi-file-text-fill"></i> 论文与成果
portfolio-subtitle:
  en: <i class="bi bi-collection"></i> Portfolio
  zh: <i class="bi bi-collection"></i> 作品集
resume-links:
  en: <a href="周方亚诺_英文简历.pdf" target="_blank" rel="noopener"><i class="bi bi-file-earmark-pdf"></i>Download CV (EN)</a><a href="周方亚诺_中文简历.pdf" target="_blank" rel="noopener"><i class="bi bi-file-earmark-pdf"></i>Download CV (ZH)</a>
  zh: <a href="周方亚诺_中文简历.pdf" target="_blank" rel="noopener"><i class="bi bi-file-earmark-pdf"></i>下载中文简历</a><a href="周方亚诺_英文简历.pdf" target="_blank" rel="noopener"><i class="bi bi-file-earmark-pdf"></i>下载英文简历</a>
copyright-text:
  en: '&copy; Noah Zhou 2026. All Rights Reserved.'
  zh: '&copy; 周方亚诺 2026. 保留所有权利。'
